### ISSUE TITLE
Other scripts then latin

### ISSUE THREAD

**Issue by o28o** [thesunshade/mini-sc#10]
Hi there
Hope you're doing great. 

Traveling in Thailand I found out that this and Lao Cambia Myanmar and others are not reading Suttas in Pali in Latin script but in there own scripts.

I guess that your sites are much more popular then mine and it could be so great if visitors can use sc light with their own script.

There is a great transliteration app, plugin, widget, api, photon package named Aksharamukha which is used at suttacentral.net as well.

And it should be very easy to implement. 

From their docs:
<script src="https://cdn.jsdelivr.net/gh/virtualvinodh/aksharamukha/aksharamukha-web-plugin/aksharamukha-v3.js?class=verse"></script>

Will it be interesting for you to add it to sc light? 

I really want to add it to my code but I've failed, don't know

 why)![Screenshot_20230203_070927_F12.jpg](https://user-images.githubusercontent.com/90468182/216481660-fe69ce9c-6631-406a-a8c4-fe886972a368.jpg)

![Screenshot_20230203_071028_F12.jpg](https://user-images.githubusercontent.com/90468182/216481662-4532fee5-326e-46b4-ab90-8d9431a8aafe.jpg)

![Screenshot_20230203_071056_F12.jpg](https://user-images.githubusercontent.com/90468182/216481661-06348241-7e9d-47f4-9950-09cce0f75be4.jpg)

**Comment by thesunshade** [comment]
Did you use the version of the script import where you tell the class to transliterate?

![image](https://user-images.githubusercontent.com/82448383/216483640-32009a0a-5d3f-4b2b-9471-c38839e83320.png)

I think you would want to set it like this:

```
<script src="https://cdn.jsdelivr.net/gh/virtualvinodh/aksharamukha/aksharamukha-web-plugin/aksharamukha-v3.js?class=pli-lang"></script>
```

**Comment by o28o** [comment]
Yes tried
Gives some error. And hangs. I even asked aksharamukha developers in github. But no response at all. Eerh)
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Friday, 03 February 2023, 07:47AM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
You should get into the habit of sharing the error message, lol. What was it?

**Comment by o28o** [comment]
Sorry I thought it was in the screenshot I attached
Uncaught (in promise) #<Object>

--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Friday, 03 February 2023, 08:22AM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
Huh. Did it give you a line number where the error occurred? Maybe a screenshot of the error would be the best thing. There is a promise for getting the text from SC's api, but I wonder if there is also a promise happening in the Aksharamukha script.

**Comment by thesunshade** [comment]
BTW, the developer gives his address on the about page: http://aksharamukha.appspot.com/about Sometimes people don't respond to github things quickly.

**Comment by o28o** [comment]
Unfortunately no other info.
No line numbers or other hints.
But I do that from phone. So may be its a dev browser is not advanced enough.
I'll have laptop in about may))))
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Friday, 03 February 2023, 08:40AM +07:00 from thesunshade  ***@***.*** :

**Comment by o28o** [comment]
Oh yes. I emailed him directly on Dec 29. No response)
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Friday, 03 February 2023, 08:45AM +07:00 from thesunshade  ***@***.*** :

**Comment by o28o** [comment]
And I think aksharamukha web plugin is very sensitive to other js scripts.
Because I have test page with pure html and there it works fine
https://find.dhamma.gift/ssearch.php

--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Friday, 03 February 2023, 08:45AM +07:00 from thesunshade  ***@***.*** :

**Comment by o28o** [comment]
Hi there.
How are you?
I thought I'm familiar with your code enough. 
But I couldn't manage to set default pali for cases when user opens sutta from citation input from the home page.
Could you please give a hint.
I set 
Let lang = pli
But it doesn't work

--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Friday, 03 February 2023, 09:24AM +07:00 from Pavel Katorgin  ***@***.*** :

**Comment by thesunshade** [comment]
Is you code still using local storage to remember what the user last picked as their language? Just look to see if there is `localStorage`
