### ISSUE TITLE
Autocomplete for citations

### ISSUE THREAD

**Issue by o28o** [thesunshade/mini-sc#11]
Hi there 

How are you?

Recently I've added sutta citations to autocomplete function in https://find.dhamma.gift/

It's pretty useful for reading suttas with unpredictable citations like an1.1-10 etc.

![Screenshot_20230220_070936_F12.jpg](https://user-images.githubusercontent.com/90468182/219981031-39392067-2135-4ceb-ac7c-4a589be6129c.jpg)

If you like the idea you can just add it to your sc light version

https://find.dhamma.gift/assets/js/autopali.js

**Comment by thesunshade** [comment]
Neat! I'll take a look.
