### ISSUE TITLE
Improvement: Easier sutta citation

### ISSUE THREAD

**Issue by anotatta** [thesunshade/mini-sc#16]
Thanks for this great tool.
I would like to suggest an improvement in the search string capability.
It would be helpful if the search string can be simplified rather than exact match.
For example a search with "an2.77" should produces a result (right now it produces "invalid sutta citation") rather than entering exact "an2.77-86" because the user sometime does not know that section 77 span to 86.

**Comment by thesunshade** [comment]
Thanks for the feedback!

The main reason behind this tool was to create an example of the use of the SuttaCentral API where the whole website was less than ~10kb. The whole point was to strip it down to the essentials.

Unfortunately the SC API requires that requests be made for sutta ids that perfectly match the way they appear on official pages on SC. A secondary API was created later that can handle "incorrect"/partial ids, but it's necessary to know that it is partial before deciding which to call. It might be possible to incorporate that with error handling. Will have to look into that.

In the mean time, you can always use the [citation helper app](https://sutta.readingfaithfully.org) to turn partial ids into complete ones. Just enter the partial id and then click on the SC-light logo:

![image](https://github.com/user-attachments/assets/0ea75fb0-aa05-48f3-9bf8-93ce2e9202c4)

Alternatively, https://find.dhamma.gift/sc/?q=an2.77-86 is a site based on SC-Light that has incorporated your suggestion. It has a whole bunch of other bells and whistles too.

**Comment by anotatta** [comment]
Oh, thanks for the find-dhamma site. I'll use that one.
