### ISSUE TITLE
Hide English suttaname when toggling pali

### ISSUE THREAD

**Issue by o28o** [thesunshade/mini-sc#7]
Hi there. How are you? Could you advise what I should do to hide the sutta name when switching to pali.

Dutiyasukhasutta
**Happiness (2nd)**

I checked I guess everywhere in the index.js file, but wasn't able to hide the sutta name

**Comment by thesunshade** [comment]
Ah, it's not controlled by the js. Well, not in the way you were trying. The js adds the class `hide-pali` to the body. It's in the css that you decide what that affects.

Take a look at this part of the css file:

https://github.com/thesunshade/mini-sc/blob/3e6949c18a0b0b695c59888bddab82200a920375/index.css#L224-L230

Do you understand what that's doing?

**Comment by o28o** [comment]
Ooh. Cool. Thank you. That helped
Added h1 there. 
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Sunday, 18 December 2022, 05:00PM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
I'm so happy you are using this code!

**Comment by o28o** [comment]
Using it everyday, everyday)))
Thank you so much
Didn't figure out how to reconfigure it to local files instead of api. But hopefully will
I also saw sutta difference in your projects. It's very cool, I use is not so often but when it's time for sutta diff it helps 🥰 
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Sunday, 18 December 2022, 05:49PM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
> I use is not so often but when it's time for sutta diff it helps

I'm the same. I don't use it very often, but when I do, it saves lots of time.
