### ISSUE TITLE
How to make pali default language without lang parameter

### ISSUE THREAD

**Issue by o28o** [thesunshade/mini-sc#8]
Hi there. How are you?

Could you please advice where I can change pli-eng to pali when opening texts?

I tried to change it myself in js file and didn't work. Still pli-eng is still default

```
html += `${openHtml}<span class="segment" id ="${segment}"><span class="pli-lang" lang="pi">${
          root_text[segment] ? root_text[segment] : ""
        }</span><span class="eng-lang hide-english" lang="en">${translation_text[segment]}</span></span>${closeHtml}\n\n`;
      });
```

Or I need to change something in css file? 

With Metta 
Pavel K

**Comment by thesunshade** [comment]
So you mean that when the page opens you want it to default to the Pali? Or do you mean that you only ever want Pali to be available?

Right now, the way it works is that the last view is stored in the browser's `localStorage` and then it opens in whatever that last view was. 

The html of the page never changes. It's all done through changing classes. Take a look at the function `toggleThePali()` to see how it works.

**Comment by o28o** [comment]
Thank you. 
I'll look on it. 
I'd like to have pali as default language 
Because when I press next sutta or previous, that sutta changes to pali eng. 
But of course, option to switch to English and pali English is cool and should stay. 

--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Saturday, 24 December 2022, 06:05PM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
> Because when I press next sutta or previous, that sutta changes to pali eng.

Ah, that shouldn't be happening. Or at least, that's not how it works in the original app.

Hmm.

**Comment by o28o** [comment]
May be I've broken something😅
Eveytime when I open js it's like a domanassa domanassa 
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Saturday, 24 December 2022, 06:15PM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
Yeah, something has gotten borked. When clicking the toggle button, the value in local storage doesn't change:
![image](https://user-images.githubusercontent.com/82448383/209434344-6328a643-ec9a-40c8-a289-c2d7d4abcd54.png)

-------------

OK, never mind. I think when we made the change to the three way toggle, we removed the storage of the layout variable in `localStorage`. I seem to remember having a conversation  about that. Maybe you were only interested in having the url indicate the language when you linked to it?

Each time you click on the next page link, the whole app resets. So the language will reset.

You would need to 

1. store the language value in `localStorage` each time you clicked the toggle button
2. when the app is initialized, check to see if there is anything in local storage to determine the language pref and then either
     * set the language to what is in local storage or
     * set local storage and the value to be whatever default language you wanted.

Or… you could add the language preference to the url of the previous/next links at the bottom. That might be easier, although it's not a very robust solution.

If you want

**Comment by o28o** [comment]
Oooh!! Super. Thank you. 
I'll try with localstorage. 
For now I've added the lang in urls. Does the job. 👍🙏👍

--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Saturday, 24 December 2022, 06:52PM +07:00 from thesunshade  ***@***.*** :
