### ISSUE TITLE
How to move next orev buttons to the top of the page?

### ISSUE THREAD

**Issue by o28o** [thesunshade/mini-sc#9]
Hi there

How are you?

I finally made the local copy based sc light. It even emulates api with next and prev suttas.

https://find.dhamma.gift/scm/?q=sn56.11&lang=pli

I wanted to move next and prev sutta buttons to the top of the page but I don't understand what is that))))

Looks like this part is responsible for the button location. How you generate buttons like this? I don't even know how to Google such thing😊😊😊

​ ​ ​ ​ ​ ​ ​ ? `<a href="?q=${nextSlug}&lang=${language}">${nextSlugPrint} ${nextName}<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="body_1" width="15" height="11">

​ ​ ​ ​ ​ <g transform="matrix(0.021484375 0 0 0.021484375 2 -0)">
​ ​ ​ ​ ​ ​ ​ <g>
​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ <path d="M202.1 450C 196.03278 449.9987 190.56381 446.34256 188.24348 440.73654C 185.92316 435.13055 187.20845 428.67883 191.5 424.39L191.5 424.39L365.79 250.1L191.5 75.81C 185.81535 69.92433 185.89662 60.568687 191.68266 54.782654C 197.46869 48.996624 206.82434 48.91536 212.71 54.6L212.71 54.6L397.61 239.5C 403.4657 245.3575 403.4657 254.8525 397.61 260.71L397.61 260.71L212.70999 445.61C 209.89557 448.4226 206.07895 450.0018 202.1 450z" stroke="none" fill="#8f8f8f" fill-rule="nonzero" />
​ ​ ​ ​ ​ ​ ​ </g>
​ ​ ​ ​ ​ </g>
​ ​ ​ ​ ​ </svg></a>`
​ ​ ​ ​ ​ ​ ​ : "";
​ ​ ​ }

--

**Comment by thesunshade** [comment]
I'm doing well. Glad you are still finding the code helpful.

The Prev/Next buttons are created through a common coding patter where in the html file there are dom elements hard coded in and then the javascript makes changes to those elements.

So for something simple like changing the location, you just have to move this code:

https://github.com/thesunshade/mini-sc/blob/3e6949c18a0b0b695c59888bddab82200a920375/index.html#L50-L53

To the top of the html file.

**Comment by o28o** [comment]
Yes. Your tool is my main sutta reading source now))) so I use it everyday, many times a day🙏🙏🙏
Thank you so much
I added the same block but buttons appear only once on the top of thepage.
I thought it'll be better to keep them below the sutta and just add two more above. But seems it's not as intuitive as I thought it would be done. 
Do you know why it doesn't make copy of these buttons?
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Saturday, 28 January 2023, 11:13AM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
> Do you know why it doesn't make copy of these buttons?

Ah, you want it twice. I just thought you wanted to move them. If you look in the js file you see at the top:

```
const previous = document.getElementById("previous");
const next = document.getElementById("next");
```

So the elements are captured by id and there can only ever be one id with a given name. So after the first one it finds, it ignores the rest.

If you want to control multiple elements in the same way, you would have to give them a class name an then get all those. But then you end up with an array of elements, or maybe a node list, not sure. Then to add the text by javascript you would need to loop through them.

An easier solution would be to have `top-previous` and `bottom-previous`. Then assign the inner html of both. Make sense?

**Comment by o28o** [comment]
Thank you. 
I'll try)))
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Saturday, 28 January 2023, 01:58PM +07:00 from thesunshade  ***@***.*** :

**Comment by o28o** [comment]
Hi there. 
Thank you. I did it) two pairs of prev and next buttons. https://find.dhamma.gift/sc/?q=mn129&lang=pli
I'm so pleased with pali toggle from sc light that I decided that it's a must for my project as well.
Check it out https://find.dhamma.gift/result/adhivacanas_suttanta_pali_1-2.html
I disabled English only option. So you can choose pli-eng or pli.
It's so cool. Thank you so much.


--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Saturday, 28 January 2023, 01:58PM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
I'm so happy to hear that! Great work.
